# Generated by Django 5.1.2 on 2024-10-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('kitchen', models.BooleanField(default=False)),
                ('AC', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
            ],
        ),
    ]
