# Generated by Django 5.1.2 on 2024-10-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='casa_images/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa_images', to='App.casa')),
            ],
        ),
    ]
