# Generated by Django 5.1.2 on 2024-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_casa_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa_images',
            name='images',
        ),
        migrations.AddField(
            model_name='casa_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='casa_images/'),
        ),
    ]
