# Generated by Django 5.1.2 on 2024-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_casa_images_images_casa_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
