# Generated by Django 5.1.2 on 2024-10-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_casa_latitud_alter_casa_longitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='casa',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
