# Generated by Django 5.1.2 on 2024-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_casa_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='TV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='square_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='tub',
            field=models.BooleanField(default=False),
        ),
    ]
